/**
 * sync.js
 *
 * Regenerates the component sources of the published npm package
 * (virtualui-components-lib) from the live VirtualUI platform API.
 *
 *  1. Cleans src/components/ and recreates it.
 *  2. Fetches all PUBLIC components from the API.
 *  3. Writes each component's code verbatim to src/components/{Name}/{Name}.jsx.
 *  4. Regenerates src/index.js with a named export per component.
 *
 * The API serves component code as `export const Name = ...`, so each file is
 * self-contained and index.js only needs to re-export it.
 *
 * Runs with plain Node (no dependencies) — requires Node 18+ for global fetch.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const COMPONENTS_DIR = path.join(__dirname, "src", "components");
const INDEX_PATH = path.join(__dirname, "src", "index.js");

const API_URL =
  process.env.COMPONENTS_API_URL ||
  "https://ai-powered-virtual-ui-library.onrender.com/api/component/all-components";

/**
 * Normalize a component name into a valid PascalCase JS identifier
 * used for the folder/file name.
 */
function toIdentifier(name) {
  let id = String(name || "").replace(/[^a-zA-Z0-9_$]/g, "");
  if (!id) return "Component";
  id = id.charAt(0).toUpperCase() + id.slice(1);
  if (/^[0-9]/.test(id)) id = "Comp" + id;
  return id;
}

/**
 * Extract the export name from the component code ("export const Foo = ...").
 * Falls back to the sanitized component name when no match is found.
 */
function exportNameFromCode(code, fallback) {
  const m = String(code || "").match(/export\s+const\s+([A-Za-z_$][\w$]*)/);
  return m ? m[1] : fallback;
}

async function main() {
  // Start from a clean slate — removes stale folders and the stray ".jsx" file.
  fs.rmSync(COMPONENTS_DIR, { recursive: true, force: true });
  fs.mkdirSync(COMPONENTS_DIR, { recursive: true });

  let components = [];
  try {
    const res = await fetch(API_URL, { signal: AbortSignal.timeout(90_000) });
    if (res.ok) {
      components = await res.json();
    } else if (res.status !== 404) {
      throw new Error(`API responded ${res.status}: ${await res.text()}`);
    }
    // 404 = "No public components found" -> treated as an empty list.
  } catch (err) {
    console.error("[sync] Failed to fetch components:", err.message);
    process.exit(1);
  }

  if (!Array.isArray(components)) {
    console.error("[sync] API response is not an array:", components);
    process.exit(1);
  }

  const exportLines = [];
  const seenExports = new Set();

  for (const comp of components) {
    if (!comp || !comp.code) {
      console.warn(`[sync] Skipping component "${comp?.name}" — no code`);
      continue;
    }

    const folder = toIdentifier(comp.name);
    const exportName = exportNameFromCode(comp.code, folder);

    if (seenExports.has(exportName)) {
      console.warn(`[sync] Skipping duplicate export "${exportName}"`);
      continue;
    }
    seenExports.add(exportName);

    const dir = path.join(COMPONENTS_DIR, folder);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, `${folder}.jsx`), comp.code, "utf8");

    exportLines.push(
      `export { ${exportName} } from "./components/${folder}/${folder}.jsx";`
    );
    console.log(`[sync] Wrote src/components/${folder}/${folder}.jsx -> export ${exportName}`);
  }

  const index = `// AUTO-GENERATED by sync.js — do not edit manually.\n${exportLines.join("\n")}\n`;
  fs.writeFileSync(INDEX_PATH, index, "utf8");
  console.log(`[sync] index.js updated with ${exportLines.length} exports`);
}

main().catch((err) => {
  console.error("[sync] Unexpected error:", err);
  process.exit(1);
});
